# Build settings

markdown: kramdown
permalink: pretty

port: 8000

include: ['_includes/work']
exclude: ['the_design.psd']

sass:
  sass_dir: assets/css
  style: :nested

domain: artsealive-preview.sites.dev.samcarpentier.com
url: https://artsealive-preview.sites.dev.samcarpentier.com
baseurl: ""
