#-------------------------------
# General Site Settings

title: ArtSeaLive
description: Artiste multidisciplinaire
email: artiste@artsealive.com

# NOTE: The Logo and Background image are defined in the all.sass document.

menu:
- {name: À Propos, url: '#about-me'}
- {name: Démarche Artistique, url: '#approach'}
- {name: Oeuvres, url: '#work'}
- {name: Contact, url: '#contact'}

#-------------------------------
# SEO Section

# NOTE: Providing SEO information will make this website more searchable on the internet.

seo:
  description: ''


#-------------------------------
# About Section

# NOTE: The avatar is defined in the all.sass document.

blurb: >
  Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed in semper metus. Ut nisl est, auctor dignissim erat et, ultricies congue tortor. Nulla et ultricies mauris. Etiam elementum faucibus massa in suscipit. Phasellus elementum elit vitae lorem ultricies dapibus. Integer vel ipsum egestas, efficitur lectus eu, consequat ex. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Sed in tellus non turpis pretium venenatis. Maecenas cursus est turpis, ac hendrerit libero ullamcorper dapibus. Suspendisse potenti. Donec id tempor nibh.


#-------------------------------
# Work Section

projects:
  - { name: L'abri (2010), folder: 'abri' }
  - { name: Les gardiens d'Éden (2024), folder: 'gardiens-eden' }
  - { name: Ricochets lumineux (2024), folder: 'ricochets-lumineux' }
  - { name: Vivre sous bulle (2009), folder: 'vivre-sous-bulle' }
  - { name: Échouée (20xx), folder: 'echouee' }
  - { name: Fleurs du temps (20xx), folder: 'fleurs-vent' }
  - { name: Chimie (2020), folder: 'chimie' }
  - { name: Florescence insolite (2024), folder: 'florescence-insolite' }
  - { name: Phoenix (20xx), folder: 'phoenix' }
  - { name: Urbanité (2009), folder: 'urbanite' }
  - { name: Voyage du temps (2018-2020), folder: voyage-temps}
  - { name: Voix d'un songe d'enfant (20xx), folder: 'voix-songe-enfant' }
  - { name: Sortie de l'ange (20xx), folder: 'sortie-ange' }
  - { name: Réverbération (20xx), folder: 'reverberation' }

#-------------------------------
# Contact Section

social: []
# - {icon: 'twitter', link: 'http://twitter.com/devtipsshow'}
# - {icon: 'dribbble', link: 'https://dribbble.com/travisneilson'}
# - {icon: 'behance', link: 'https://www.behance.net/travisneilson'}
# - {icon: 'youtube', link: 'https://www.youtube.com/DevTipsForDesigners'}
# - {icon: 'linkedin', link: 'http://www.linkedin.com/in/travisneilson/'}


# social network icons available: 'twitter' / 'facebook' / 'github' / 'pinterest' 'google-plus' / 'linkedin' / 'youtube' / 'instagram' / 'dribbble' / 'behance' / 'soundcloud' / 'vine'
